### ISSUE TITLE
While internals are on, the suffocating icon on your HUD occasionally pops up, without doing any harm.

### ISSUE THREAD

**Issue by Irradiation** [vgstation-coders/vgstation13#20481] opened 2018-10-28 21:41 UTC
#### Description of issue
Maybe it's the new XGM update or something, here's the thing. Whenever I have an air tank (with plenty of air), an internals mask and I decide to use my internals, even WITHOUT atmospheric leaks, I'll occasionally get the NO-AIR HUD icon appear next to my internals. I suffer no damage, do not gasp or get any message, then it disappears after a second or three. This happens every 5 minutes or so. It also occurs when there are atmospheric leaks/no air in the area.

#### Difference between expected and actual behavior
To not have a popup claiming I'm suffocating when I'm actually fine.

#### Steps to reproduce
1 - Put air tank in pockets.
2 - Set air tank pressure to 16 kPa (This has been safe for months now).
3 - Put internals mask on.
4 - Activate internals.
5 - Wait a bit and then [NO AIR] (or suffocating] HUD icon near the Internals button will show up for a few seconds.

#### Length of time in which bug has been known to occur

About 1 or 2 weeks now. I've changed BYOND versions to 512.1448 yesterday, but it had been happening for much longer. I used to be on 512.1426 & 1427.

[bugfix][consistency][help][ui]

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment] 2018-10-28 22:08
dupe of #20003

The pressure bar turns BRIGHT RED at 16 anyways with 17 being the last not-red number

**Closed** 2018-10-28 22:28 UTC
Labels: Not A Bug

**Comment by Exxion** [comment] 2018-10-28 23:31
It's harmless anyway
You take 1 oxy damage per tick the warning appears, and heal 5 per tick it does not
