### ISSUE TITLE
infrared emitter

### ISSUE THREAD

**Issue by AutismSpider** [vgstation-coders/vgstation13#2847] opened 2015-02-07 07:01 UTC
They do nothing.

They don't work for bombs.(tank transfer  and grenade)

When use for grenades got screwdriver set them off.

**Comment by frangi** [comment] 2015-02-10 10:51
They seem to not detected human movement, but they detect mommi movement. They still don't send any kind of signal tho.

**Comment by ConkerDev** [comment] 2015-09-18 18:51
They dont even seem to be spawnable anymore.

**Comment by ConkerDev** [comment] 2015-10-27 09:36
Pomf killed them. Unless its unintended, its not a bug

**Comment by PJB3005** [comment] 2015-10-28 18:22
Pomf killed them because somebody (N3X15 or pomf) tried to move them to beams, but fucked up and they caused infinite loops.

**Comment by clusterfack** [comment] 2015-10-28 21:00
Well all beams caused infinite loopies, but that was fixed though

**Comment by Kurfursten** [comment] 2015-11-02 22:16
Probably can safely remove Bug from this one though, given that it's definitely just Feature Loss now that it's out of the game completely.

**Comment by PJB3005** [comment] 2015-11-02 22:17
It was removed as an "OH FUCK" due to a bug, I'd say it's worth keeping the tag.

**Comment by clusterfack** [comment] 2015-11-02 22:25
Its not out of the game uta just disabled, someone had ought to fix it

**Comment by FudgePucker** [comment] 2015-11-16 17:03
We can't fix this bug because it would be a feature while we are in a feature freeze.
We can't get out of the feature freeze because of bugs like these.

Comment out infrared emitters and close this issue. Open a feature request.

**Comment by PJB3005** [comment] 2015-11-16 17:41
They're already commented out.

**Comment by FudgePucker** [comment] 2015-11-16 18:25
So then this isn't a bug its a feature request

**Comment by clusterfack** [comment] 2015-11-16 18:38
Stop trying to declassify things as bugs

**Comment by ConkerDev** [comment] 2015-12-16 10:07
The assembly system may have changed the working of emitters. Please recheck

**Comment by PJB3005** [comment] 2015-12-16 12:13
@ConkerDev it had nothing to do with that, it was the beam that the emitters used that caused infinite loops.

**Comment by Cisrox** [comment] 2016-01-01 04:49
These things need to be fixed, they're cool as shit.

**Comment by AutismSpider** [comment] 2016-01-01 06:26
Good for making trap bombs when they did work just got wait see if they dont bug out the serb and crash it with runtime errors

**Comment by ConkerDev** [comment] 2016-04-18 16:16
This has been one of the most whined about feature losses. They should be remade.

**Comment by AutismSpider** [comment] 2016-04-18 17:37
They need to be remade with the new  emitter code

**Comment by PJB3005** [comment] 2016-04-18 18:42
They were.

Pomf did it. Because he fucked up and didn't test them they were OH GOD PANIC removed instantly and never readded.

**Comment by Probe1** [comment] 2016-05-06 07:20
fix it

**Comment by jknpj** [comment] 2017-12-18 17:25
RIP IR emitters

**Closed by jknpj** 2017-12-18 17:25 UTC
Labels: Bug / Fix, Feature Loss
