### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Nurse Spider Behaviour problem

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#4952] opened 2015-06-13 15:21 UTC
> Revision (Should be above if you're viewing this from ingame!)
> 0bb8b9f45d34c5a76ee6a8c6486b799550365f7b
> 
> General description of the issue
> After observing spiders several round I found some problem in the nurse Behavior that make them act stupide
> 
> issues
> 1. Nurse AI find a new target at the begining of laying a web instead of at the end, thus they'll start making webs (cocoons work fine) and get a new target right aways making them move before they finish
> 2. Nurse Spider will not attack windows and grille between them and a cocoon target, as this take priority over laying webs, they will endlessy try to get there whitout being able to

**Comment by 9600bauds** [comment] 2015-06-14 00:29
~~They also lack a sanitycheck for webbing, meaning even if they get dragged off while they are webbing something it will succeed anyways~~ could not reproduce anymore
I can take a look at this since I've already been there in the code

**Comment by 9600bauds** [comment] 2015-12-16 08:48
I didn't take a look at this in the end

**Comment by jknpj** [comment] 2017-12-18 17:29
Fixed by N3X

**Closed by jknpj** 2017-12-18 17:29 UTC
Labels: Bug / Fix, Needs Moar Testing
