### ISSUE TITLE
Fabricators eating materials from silicon inventories

### ISSUE THREAD

**Issue by AutismSpider** [vgstation-coders/vgstation13#8934] opened 2016-03-20 02:10 UTC
So as a Engi borg/Mommi i make a stack of 50 iron/glass then make 50 more so humans can use it or to stick in a fab to make parts etc

Sticking what the mommi/engi borg can't hold into Fabs imputers etc eats all of the stacks they made+ whats store in them in one go so you can over load a Fab with iron glass gold etc

**Comment by 9600bauds** [comment] 2016-03-20 08:14
Cannot reproduce before or after the "new material stacking stuff"
Bug in question doesn't sound even tangentially related to the "new material stacking stuff", but I guess thanks for reporting this one.

Did this happen with a MoMMI or a borg?
Exactly what material did this happen with?
What fabricator did this happen with?
Did the silicon or someone else load the sheets in the fabricator?

**Comment by Probe1** [comment] 2016-03-20 17:56
It's pretty easy to  reproduce..

1.  Become a MoMMI.
2.  Use your material synthesizer to make 50 sheets of metal twice (100 total).  The second stack of 50 will fall on the ground.
3.  Pick up the stack on the ground and load it into an exosuit fabricator.
4.  It will take both the metal you're holding AND the metal from the mommis internal container, adding all 100 sheets instead of the 50 inserted.

**Comment by Probe1** [comment] 2016-03-20 18:02
Tested with an autolathe and glass (compared to exosuit fabricator and metal)

Reproducible as described above.

**Comment by Intigracy** [comment] 2016-03-20 18:06
Does it only eat out of your inventory if you put it in, or if anyone puts it in?

**Comment by Probe1** [comment] 2016-03-20 18:14
@Intigracy 
Only if I put it in.  I tested with @musgardtiger and it did not take from my inventory when he inserted metal.  He was standing here

![image](https://cloud.githubusercontent.com/assets/8550416/13906151/097ac59e-eea6-11e5-801b-c7981a3b8fe6.png)

**Comment by 9600bauds** [comment] 2016-03-20 23:43
Literally could not reproduce doing exactly what you described, what the fuck

**Comment by 9600bauds** [comment] 2016-03-21 00:04
Turns out my branch was outdated by 2 days, so somehow this bug was caused by something merged in the last 2 days.
I honestly have not been up to date in github or the game in general due to real life so I have no clue what's been going on. I do know that borg inventory code is a mess, though.

**Comment by Probe1** [comment] 2016-03-21 00:22
That's a very useful clue as it turns out.

**Comment by Intigracy** [comment] 2016-03-21 00:52
I can't find a PR that would cause this.

**Comment by 9600bauds** [comment] 2016-03-21 02:34
No, checked out just before and just after the stacking change and could not reproduce the bug

**Comment by Intigracy** [comment] 2016-03-21 02:35
Is it happening to borgs too, or just mommis?

**Comment by Probe1** [comment] 2016-03-21 06:56
Did not test.

**Comment by Shadowmech88** [comment] 2019-11-01 19:38
No longer happens.
![image](https://user-images.githubusercontent.com/3991927/68051331-2d409c80-fcb5-11e9-8d4b-d3b976aff9b7.png)
I added 50 sheets to an exosuit fabricator while also having 50 sheets in my inventory, and the sheets in my inventory were just fine.

**Closed by Shadowmech88** 2019-11-01 19:38 UTC
Labels: Bug / Fix
