### ISSUE TITLE
(WEB REPORT BY: fozzington REMOTE: 198.245.63.50:7777) Crew Monitor Console Bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [vgstation-coders/vgstation13#5576] opened 2015-07-28 05:58 UTC
-When changing z-levels, the list of (active personnel? Unsure how to properly describe it) rarely, if ever, properly updates, resulting in personnel from the first z-level still being shown despite the shift (this can be evidenced in personnel icons showing up in places that would make no rational sense, as well as a failure to properly show people who may actually exist on the z-level being shown)
- The crew monitoring console tends to break about 75% of the time after usage, possibly due to attempting to shift z-levels, thus forcing a reset of the client to re-enable its function

As it stands, the current implemented cmc makes it near-impossible to track anyone not on the main station. Perhaps that is meant to be a feature, but considering the old cmc was a lot more effective in this regard, perhaps some adjustments may be necessary

**Comment by ShiftyRail** [comment] 2019-04-29 09:34
Duplicate of #5945

**Closed by ShiftyRail** 2019-04-29 09:34 UTC
Labels: Bug / Fix, UI
