### ISSUE TITLE
Right-clicking a job preference causes any "High" to go to "Medium" no the state of what you click.

### ISSUE THREAD

**Issue by RaccoonBro** [vgstation-coders/vgstation13#18046] opened 2018-04-08 18:34 UTC
Example:
![Example](https://i.imgur.com/DfUQTq5.gif)

It doesn't matter if you right click Medium to go down to Low, any job with High automatically heads down to Medium for some reason.

**Comment by DamianX** [comment] 2018-04-08 20:54
duplicate of #8235

**Closed by DamianX** 2018-04-08 20:54 UTC
Labels: Bug / Fix
