### ISSUE TITLE
Blood causes massive lag

### ISSUE THREAD

**Issue by d3athrow** [vgstation-coders/vgstation13#5875] opened 2015-09-28 04:21 UTC
likely to be related to it's constant calling of Blend.

**Comment by 9600bauds** [comment] 2015-12-16 08:29
Could you elaborate a little more? Is this still an issue?

**Comment by PJB3005** [comment] 2015-12-16 12:21
@9600bauds blood uses BYOND's icon operations, a **lot**.

And BYOND icon operations are **really fucking slow**.

**Comment by 9600bauds** [comment] 2015-12-16 18:15
Blood in containers, blood splatters, blood on people?

**Comment by PJB3005** [comment] 2015-12-17 00:06
Blood splatters

**Comment by 9600bauds** [comment] 2015-12-22 05:18
According to @wwjnc this could be fixed by either giving blood an obj_overlay with blendtype set to MULTIPLY, or by giving it a "color matrix" of some sort.

There is another factor why blood is laggy, and that's because the code for spreading diseases is fucking TERRIBLE and I believe it checks for blood in the tile of every single human, constantly, when the same fucking shit could be done in a non-retarded manner through usage of Crossed() or Entered().

**Comment by optimumtact** [comment] 2015-12-26 08:59
are you combing the decals so there is only one on a tile for each type?

**Comment by gbasood** [comment] 2016-02-17 00:53
Could we fix this with the new color var?

**Comment by clusterfack** [comment] 2016-02-17 10:03
Yeah probably, I would have already done it if I knew more about what makes icons look the way they do

**Comment by Imagebard** [comment] 2016-05-16 11:39
For some reason I think I remember someone changing blood a while back.
Closeable?

**Comment by ghost** [comment] 2016-05-17 01:59
@Imagebard nope, still shit as always.

**Comment by gbasood** [comment] 2016-08-03 02:03
I started on it but the problem is that the gibs don't color properly
Blood splatters are already monochromatic and can be color'd but gibs look stupid because they're red and pink
If someone wants to redo gibs monochromed then it would be easy to resolvea

**Comment by gbasood** [comment] 2016-08-03 02:04
#8644 is the work I did but I fucked it all up at some point

**Comment by ghost** [comment] 2016-08-03 02:35
@gbasood you can two-tone gibs with an overlay that doesn't take the parent colour.

**Comment by clusterfack** [comment] 2016-08-03 02:47
hell you could have r on one channel and g on another channel and then use a color matrix to modify those

**Comment by ghost** [comment] 2016-08-03 03:02
@clusterfack that too would work.

**Comment by PJB3005** [comment] 2016-08-03 12:26
You could 3 tone them.

**Comment by gbasood** [comment] 2016-08-03 16:11
cool do it

**Comment by gbasood** [comment] 2017-01-07 19:54
@Probe1 did someone actually do this

**Comment by PJB3005** [comment] 2017-01-07 19:56
no

**Comment by Shadowmech88** [comment] 2017-10-23 07:27
@clusterfack says that this is no longer the case.

**Comment by gbasood** [comment] 2017-10-23 18:48
Unless someone changed something with blood, or BYOND got better, it's still the case.
Please try making an excessive amount of blood locally to see if this is still the case first.

**Comment by Exxion** [comment] 2017-10-23 18:50
This is a different issue. It's talking about serverside lag, not clientside lag.

**Comment by gbasood** [comment] 2017-10-23 18:50
o-oh

**Closed by Exxion** 2017-10-23 18:50 UTC
Labels: Performance
