### ISSUE TITLE
paying from a vendor can delete all your virtual wallet funds

### ISSUE THREAD

**Issue by pedr69** [vgstation-coders/vgstation13#33209] opened 2022-09-03 02:19 UTC
[bugfix]
paying for expensive stuff out of vendors will empty your virtual wallet

say you have 99 bucks in your virtual wallet, and 100 in the bank
trying to buy something that costs 200cr will tell you "there's not enough in your wallet, do you want to use your bank funds as well?"
if you press yes, your virtual wallet gets emptied, and the transaction denied, because you didn't have enough money in the bank account
happened to me a couple times now when vending diamond pickaxes or expensive stuff out of the old vendortron

**Comment by Eneocho** [comment] 2022-09-03 07:03
Known bug, nobody has bothered to fix it. Duplicate of #27803 and #30316.

**Comment by pedr69** [comment] 2022-09-03 10:21
there's also several ways to empty someone's bank account without their pin, despite the account security settings set to "require pin"
it'll be a while before i can wrap my head around the economy/utils.dm

**Comment by Eneocho** [comment] 2022-09-03 18:15
The bank account configuration is to deter someone stealing your funds by getting your ID, the many ways to heist someone are for the most part intended behaviour.

**Comment by pedr69** [comment] 2022-09-03 22:04
>stealing your funds by just stealing your ID

but that's exactly what happens, even with advanced security settings set someone can empty your bank
i'd expect your ID's virtual wallet to be the only thing that can be emptied, and your bank only if you have it set to no security(and someone has your ID/bank account number)

**Comment by Eneocho** [comment] 2022-09-04 00:00
Keyword is deter, not stop.

**Closed** 2022-10-11 05:47 UTC
Labels: Bug / Fix
