### ISSUE TITLE
Crew Monitor Console is fucking up again

### ISSUE THREAD

**Issue by aceedex** [vgstation-coders/vgstation13#13216] opened 2017-01-02 00:00 UTC
it's not showing the station minimap when you click on it, like so
https://puu.sh/t7KAi/cbcd2f5bda.png

It's also doing that thing where if you try to change z leves the input won't register and goes into the chat bar instead, which was fixed some time ago but seems to be happening again

**Comment by Probe1** [comment] 2017-01-02 00:09
all of the minimap consoles are  😢

**Comment by PJB3005** [comment] 2017-01-02 00:27
"again"

**Comment by Probe1** [comment] 2017-01-02 00:35
At this point I'm thinking we poach something from another server that handles it in a way more sane and robust way that doesn't break every 6 months.

**Comment by PJB3005** [comment] 2017-01-02 00:41
That fix would be reverting it to Nano and moving Nano's JSON to native BYOND.

**Comment by Probe1** [comment] 2017-01-02 00:46
I know some of these words.

**Comment by BobdaBiscuit** [comment] 2017-01-02 04:13
Don't you just have to regenerate the minimaps with the verb?

**Comment by Probe1** [comment] 2017-01-02 04:43
I have no idea what that verb may be.

**Comment by Exxion** [comment] 2017-01-02 05:07
I'm convinced this is a BYOND bug
Assuming it's still the same issue, it's a problem with caching, but that shouldn't be possible

**Comment by Ephx1** [comment] 2017-01-02 07:57
#5945
never4get

**Comment by uazuaz** [comment] 2017-01-02 10:26
changing the z-level could be done the same way as the bhangmeter: click the "change z-level" button and choose from the list of available z-levels.

**Comment by PJB3005** [comment] 2017-01-02 12:33
Bhangmeter is still Nano.

That's why it actually fucking works.

**Comment by BobdaBiscuit** [comment] 2017-01-02 15:07
Ya gotta press the "Debug Verbs" in the debug category, then under the mapping category generate nanoUI maps etc.

@Probe1

**Comment by Shadowmech88** [comment] 2018-10-24 07:16
Tested, works fine for me.
Is this one of those bugs that only shows up sometimes/for some people?

**Comment by Exxion** [comment] 2018-10-24 15:52
Pretty sure it was, but the image is gone so I'm not sure

**Comment by Shadowmech88** [comment] 2018-10-24 20:36
I'm just unsure if I should close it just due to being unable to reproduce, because it's currently listed as one of the hard bugs for October.

**Comment by Exxion** [comment] 2018-10-25 21:35
Not even sure it still happens
If it's the bug I think it is, I'm about 95% sure it was a BYOND bug, which may well have been fixed at some point

**Closed by Exxion** 2018-10-25 21:35 UTC
Labels: Bug / Fix
